/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yhj_jnitest_JNITest */

#ifndef _Included_com_example_yhj_jnitset_JNITest
#define _Included_com_example_yhj_jnitset_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yhj_jnitset_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yhj_jnitset_JNITest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
